### ISSUE TITLE
Const attribute issue in node parameters

### ISSUE THREAD

**Issue by daniel-larraz** [coco-team/lustrec#10]
In the following example, lustrec classifies the `y` parameter as a constant parameter, which causes an exception when parsing the node call:

```
node f(const x:real; y: real) returns (ok: bool);
let
  ok = y < x;
tel

node top(x: real) returns (ok: bool);
let
  ok = false -> f(23.2, x);
tel
```

**Comment by ploc** [comment]
Shall be solved in 7d640c889e50fa8e65b
