### ISSUE TITLE
Calling node in an assert (2)

### ISSUE THREAD

**Issue by daniel-larraz** [coco-team/lustrec#12]
The following code fails with `Typing error: Unknown value identifier fall`:

```
node fall(in: bool) returns (out: bool) ;
let
  out = false -> (not in) and pre in ;
tel

node top (z: bool) returns (ok: bool);
let
  assert fall(z) => not ok ;
  ok = true;
tel
```

**Comment by ploc** [comment]
This is more tricky. Causality is not evaluated on asserts expressions. I am working on it.

**Comment by agurfinkel** [comment]
This is a big show stopper for us since it requires massive manual change of our input. Hope this is not too difficult.

**Comment by ploc** [comment]
commit 7352a936e96e should solve the issue. Check and give me uptate
