### ISSUE TITLE
Error: Unbound module Num 

### ISSUE THREAD

**Issue by kumori123** [coco-team/lustrec#15]
Hi，
I‘m now trying to install lustreC on my Ubuntu 20.04(Virtual machine). And I encounted an error “Error: Unbound module Num” after I input "make". Could you give me some suggestions?

**Comment by ploc** [comment]
Please try to use the latest release at https://github.com/Embedded-SW-VnV/lustrec/releases/tag/lustrec-1.7-Xia-Huai

**Comment by kumori123** [comment]
Thanks!
